# Generated by Django 4.2.4 on 2023-08-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('read_more_link', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='images/about-img.jpg')),
            ],
        ),
    ]
