# Generated by Django 4.2.4 on 2023-08-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='google_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='linkedin_link',
            field=models.URLField(blank=True),
        ),
    ]
