# Generated by Django 4.2.4 on 2023-08-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_info_facebook_link_info_google_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='company_description_1',
            field=models.TextField(default=1),
        ),
    ]
