# Generated by Django 4.2.4 on 2023-08-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_footer_description_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='company_name_link',
            field=models.URLField(blank=True, default=1),
        ),
    ]
