# Generated by Django 4.2.4 on 2023-08-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_galleryimage_title_alter_galleryimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='title',
        ),
    ]
